server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: http://localhost:9191/
          predicates:
            - Path=/doctorservices/**
        - id: patient-service
          uri: http://localhost:9192/
          predicates:
            - Path=/patientservices/**
        - id: appointment-service
          uri: http://localhost:8181/
          predicates:
            - Path=/appointmentservices/**
        - id: pressure-service
          uri: http://localhost:9193/
          predicates:
            - Path=/pressureservices/**
        - id: authorization-service
          uri: http://localhost:9190/
          predicates:
            - Path=/oauth/**

