spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pressureDataBase?createDatabaseIfNotExist=true
    username: root
    password: Rootpassword@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true

  application:
    name: pressure

server:
  port: 9193