

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/patientDataBase?createDatabaseIfNotExist=true
    username: root
    password: Rootpassword@123
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true

  application:
    name: patient-service

server:
  port: 9192

eureka:
  client:
    service-url:
      defaultZone: http://localhost:5555/eureka